# Generated by Django 4.2 on 2023-05-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destiantion',
            new_name='destination',
        ),
    ]
